### ISSUE TITLE
Changing Lables Doesn't Work

### ISSUE THREAD

**Issue by ftaker887** [hkchengrex/Mask-Propagation#1]
Hello, amazing application! The problem I'm having seems to be that changing labels doesn't work. I've tried both the number pad and number keys to no avail. Everything else is working as intended though.

**Comment by hkchengrex** [comment]
Did you specify the number of objects (`--num_objects`)? By default there is only one object and thus you cannot change the label.

**Comment by ftaker887** [comment]
> Did you specify the number of objects (`--num_objects`)? By default there is only one object and thus you cannot change the label.

You're awesome. That did the trick. Thank you!
