### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#11]
How many GPUs do you need to test on Davis and YouTube?I keep reporting memory errors during my tests.I directly used the model trained by static pictures for VOS training, skipping the pre-training of BL30K. Is that OK?

**Comment by hkchengrex** [comment]
Test: One 11GB GPU.
Yes.

**Comment by longmalongma** [comment]
> Test: One 11GB GPU.
> Yes.



> Test: One 11GB GPU.
> Yes.

Did an 11GB GPU seem inadequate during testing?Can you specify what block of GPU it is?Or can we test with multiple GPUs?


![image](https://user-images.githubusercontent.com/40291722/115333563-7992db80-a1cc-11eb-90cb-d1283cffbf05.png)
![image](https://user-images.githubusercontent.com/40291722/115333595-83b4da00-a1cc-11eb-9207-581c9d850093.png)

**Comment by hkchengrex** [comment]
You are probably doing something wrong. The memory is full on all four GPUs already!

**Comment by longmalongma** [comment]
> Test: One 11GB GPU.
> Yes.

@hkchengrex  This ok? I've tried this and I'm still out of memory

CUDA_VISIBLE_DEVICES=0,1 python eval_davis.py


> You are probably doing something wrong. The memory is full on all four GPUs already!

I got it!
