### ISSUE TITLE
How do I get quantitative results after testing on the DAVIS 2016 dataset?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#13]
Hi, how do I get quantitative results after testing on the DAVIS 2016 dataset?

**Comment by hkchengrex** [comment]
Use the official code: https://davischallenge.org/davis2016/code.html

**Comment by longmalongma** [comment]
> Use the official code: https://davischallenge.org/davis2016/code.html

Ok,thanks!
