### ISSUE TITLE
Do I need to manually merge UTF-8 "BL30K_A, B, and C into the BL30K directory after the data set BL30K is downloaded?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#16]
Do I need to manually merge UTF-8 "BL30K_A, B, and C into the BL30K directory after the data set BL30K is downloaded?I see that your code reads 'JPEGImages and 'Annotations' directly.
![image](https://user-images.githubusercontent.com/40291722/115687848-287e1580-a38d-11eb-82ee-33b31d961e93.png)

**Comment by longmalongma** [comment]
> Do I need to manually merge UTF-8 "BL30K_A, B, and C into the BL30K directory after the data set BL30K is downloaded?I see that your code reads 'JPEGImages and 'Annotations' directly.
> ![image](https://user-images.githubusercontent.com/40291722/115687848-287e1580-a38d-11eb-82ee-33b31d961e93.png)

@hkchengrex Or do you train on BL30K_A first and then train on BL30K_B when you're done?

**Comment by hkchengrex** [comment]
Each of them should be a zip file and they shall merge automatically when extracted in the same folder. In other words, they should be merged.

**Comment by longmalongma** [comment]
> Each of them should be a zip file and they shall merge automatically when extracted in the same folder. In other words, they should be merged.

Ok, thanks for your reply!
