### ISSUE TITLE
how to save the feature map of manymemory frames?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#17]
There is a part of your code that I don't understand. Should the memory frame be stored separately, or should the key-value feture map and the content feature map of the memory frame be connected together to save?Which line represents the memory frame saved?

**Comment by hkchengrex** [comment]
https://github.com/hkchengrex/Mask-Propagation/blob/b5d8e61c87e1944426c3aed43685fd0eb336353a/inference_core.py#L93

**Comment by longmalongma** [comment]
> https://github.com/hkchengrex/Mask-Propagation/blob/b5d8e61c87e1944426c3aed43685fd0eb336353a/inference_core.py#L93

![image](https://user-images.githubusercontent.com/40291722/115854768-27b4b480-a45d-11eb-8b4e-17b6261d6149.png)
有一点我不理解，将内存帧编码为键值特征图和内容特征图后，将所有内存帧的键值特征图和内容特征图各自连接到一起，然后读取，问题在于将所有帧的键值特征图和内容特征图拼接到一起会不会造成特征混合，无法保留和读取每一个内存帧的键值特征图和内容特征图？

**Comment by hkchengrex** [comment]
No, the entries are still corresponding.

**Comment by longmalongma** [comment]
> No, the entries are still corresponding.

Ok, thanks.

**Comment by longmalongma** [comment]
> https://github.com/hkchengrex/Mask-Propagation/blob/b5d8e61c87e1944426c3aed43685fd0eb336353a/inference_core.py#L93

@hkchengrex 你的这个inference_core包在其他地方并没有调用哦？不调用这个包在网络中怎么实现中间内存帧的保存？还有一个问题顺便也请教一下，您的训练网络和stm的训练网络的区别在哪里？






![image](https://user-images.githubusercontent.com/40291722/116205453-5f2ea400-a770-11eb-995b-dc0f5c5cce19.png)

**Comment by longmalongma** [comment]
> > https://github.com/hkchengrex/Mask-Propagation/blob/b5d8e61c87e1944426c3aed43685fd0eb336353a/inference_core.py#L93
> 
> @hkchengrex 你的这个inference_core包在其他地方并没有调用哦？不调用这个包在网络中怎么实现中间内存帧的保存？还有一个问题顺便也请教一下，您的训练网络和stm的训练网络的区别在哪里？
> 
> ![image](https://user-images.githubusercontent.com/40291722/116205453-5f2ea400-a770-11eb-995b-dc0f5c5cce19.png)



> No, the entries are still corresponding.

@hkchengrex 训练的额时候为什么没有内存帧的拼接操作？训练网络不需要保存内存帧吗？

**Comment by hkchengrex** [comment]
For training look at model/model.py

I have already listed the rough differences in the readme file. For the exact differences, you can always refer to the code (that's what they are for).

**Comment by longmalongma** [comment]
![image](https://user-images.githubusercontent.com/40291722/116228621-197dd580-a788-11eb-8400-b7f6205efa40.png)
95-96 lines of code are memory frame saved?

**Comment by hkchengrex** [comment]
Yes.

**Comment by longmalongma** [comment]
> Yes.

Ok, thank you very much!
