### ISSUE TITLE
How to install thinplate?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#2]
Hi, thanks for your great work. How to install thinplate?
/Mask-Propagation-main/dataset/tps.py", line 4, in <module>
    import thinplate as tps
ModuleNotFoundError: No module named 'thinplate'

**Comment by hkchengrex** [comment]
Does `pip install git+https://github.com/cheind/py-thin-plate-spline` work for you?

**Comment by longmalongma** [comment]
> pip install git+https://github.com/cheind/py-thin-plate-spline
Sorry, it still doesn't work，Do you have a better way to install ｉｔ?


$ pip install git+https://github.com/cheind/py-thin-plate-spline
Collecting git+https://github.com/cheind/py-thin-plate-spline
  Cloning https://github.com/cheind/py-thin-plate-spline to /tmp/pip-568ni9jk-build
fatal: unable to access 'https://github.com/cheind/py-thin-plate-spline/': Operation timed out after 0 milliseconds with 0 out of 0 bytes received

**Comment by hkchengrex** [comment]
That's weird... It works on my machine.
Try cloning it manually `git clone https://github.com/cheind/py-thin-plate-spline.git` and do `pip install -e .` inside the cloned folder.

**Comment by longmalongma** [comment]
> That's weird... It works on my machine.
> Try cloning it manually `git clone https://github.com/cheind/py-thin-plate-spline.git` and do `pip install -e .` inside the cloned folder.

Thanks, 
pip install git+git://github.com/cheind/py-thin-plate-spline
it works.
