### ISSUE TITLE
How to run two copies of your code at the same time?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#21]
![image](https://user-images.githubusercontent.com/40291722/116173951-0f37e900-a740-11eb-9e75-259d55b3a617.png)

I have duplicated two copies of your code and made small changes in the duplicated code respectively. When one is being trained, the other one cannot be trained. If the two codes are trained at the same time, what parameters need to be changed?One of my computers has 4 2080ti, the memory is enough.

**Comment by hkchengrex** [comment]
Change the port number in `--master_port 9842`. They cannot use the same port.

**Comment by longmalongma** [comment]
> Change the port number in `--master_port 9842`. They cannot use the same port.

OK,thanks. Can I change 9842 to any number?What does 9842 mean?
@hkchengrex

**Comment by hkchengrex** [comment]
It is a port number. As long as that port is not used.

**Comment by longmalongma** [comment]
> It is a port number. As long as that port is not used.

Ok, I got it, thanks!
