### ISSUE TITLE
about batch size

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#22]
The default value of your batch_size is 1. If we increase the batch size, will the accuracy be improved? Have you done any relevant experiments?

**Comment by hkchengrex** [comment]
The default batch size is not 1, I don't know where do you get that from. I haven't tried larger batch sizes -- I have limited resources.

**Comment by longmalongma** [comment]
> The default batch size is not 1, I don't know where do you get that from. I haven't tried larger batch sizes -- I have limited resources.

Sorry, I made a mistake, I set the batch size to 1.
