### ISSUE TITLE
Is it possible to further improve the accuracy by pre-training with other static images and virtual video?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#23]
Is it possible to further improve the accuracy by pre-training with other static images and virtual video?Such as COCO dataset.

**Comment by hkchengrex** [comment]
Maybe. I did not use COCO in this project mainly for training efficiency only.

**Comment by longmalongma** [comment]
> Maybe. I did not use COCO in this project mainly for training efficiency only.

Ok, thanks, I will try it!
