### ISSUE TITLE
如何取所有内存帧中的前一帧？

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#25]
您好，有个问题想请教下，
![image](https://user-images.githubusercontent.com/40291722/116517834-14dd2c80-a902-11eb-9533-e58776aa157c.png)

这是将所有内存帧和当前帧的内存读取操作，如果说只利用当前帧的前一帧进行匹配的话，如果去内存帧的最后保留的一帧，换句话说如何取前一帧？代码中如何实现？感谢。

**Comment by hkchengrex** [comment]
I cannot really solve your implementation problems for you...
Some hints: https://github.com/hkchengrex/Mask-Propagation/blob/b5d8e61c87e1944426c3aed43685fd0eb336353a/model/network.py#L43 tells you how the tensor is arranged. Indexing in the time dimension gives you features for different frames.

**Comment by longmalongma** [comment]
> tells you how the tensor is arranged. Indexing in the time dimension gives you features for different frames.

这里mk形状中，B是batch？CK是特征通道数？T是帧的数目？W,H分别为像素的宽和高，这样的理解对吗？

**Comment by hkchengrex** [comment]
Yes.

**Comment by longmalongma** [comment]
> Yes.

Ok, thanks!
