### ISSUE TITLE
utf-8''BL30K_c.zip里面包含了 utf-8''BL30K_c.tar文件

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#26]
在下载BK30K数据集时，utf-8''BL30K_c.zip里面包含了 utf-8''BL30K_c.tar文件，导致无法解压，其他几个文件都是tar格式的，您遇到过这个问题吗？

**Comment by hkchengrex** [comment]
All of them should be tar files. I have no idea where do you get the zip.

**Comment by longmalongma** [comment]
> All of them should be tar files. I have no idea where do you get the zip.

Thanks, I made some mistakes.
