### ISSUE TITLE
some question about codes

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#27]
您好，在您的代码中我有个疑问想请教一下，如果我对meige每个帧分别保存两个key特征图和两个value特征图，如下：

![image](https://user-images.githubusercontent.com/40291722/116778490-c6b45e80-aaa4-11eb-9ce6-3f2d33cf052b.png)

应对PropagationModel中的self.PNet(Fs[:,0], Ms[:,0])也分别对应两个key特征图和两个value特征图？
![image](https://user-images.githubusercontent.com/40291722/116778570-3b879880-aaa5-11eb-9605-c2cc25c168ef.png)
是不是对应在PropagationNetwork的segment中的输入是不是也要对应两个key特征图和两个value特征图？
除外之外，还需要做哪些改进吗？
![image](https://user-images.githubusercontent.com/40291722/116778750-6cb49880-aaa6-11eb-8f05-5019c65c1745.png)

**Comment by hkchengrex** [comment]
Looks like multi-head attention?
You would also need to change how the attention work, i.e., MemoryReader.

**Comment by longmalongma** [comment]
> oks like multi-head attention?

Yes, I want to try it.  Apart from the need to modify the MemoryReader, there should be no other places to modify, right?
