### ISSUE TITLE
About BK30K

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#28]
作者您好，我将BL30K的6个压缩包全部下载好，并全部解压之后，在进行第二个阶段的预训练时报错是找不到data/dangjisheng/BL30K/a/BL30K/Annotations/kea03423/00020.png'，不知道为什么？我是把6个文件压缩包全部下载好而且全部解压在一个目录下的，为什么会报错缺少文件？期待您的回复。

![image](https://user-images.githubusercontent.com/40291722/116870702-8f30e800-ac45-11eb-9bfe-e9c638fa58cf.png)

![image](https://user-images.githubusercontent.com/40291722/116870754-ae2f7a00-ac45-11eb-939a-938275f163a9.png)

**Comment by hkchengrex** [comment]
Duplicate #29
