### ISSUE TITLE
How do I get the penultimate frame?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#30]
![image](https://user-images.githubusercontent.com/40291722/117007675-8101cb00-ad1c-11eb-82b4-7e0820f1a392.png)

How do I get the penultimate frame?  Am I doing it right?

**Comment by hkchengrex** [comment]
I don't know... What are you trying to do? There should be three frames so `Fs[:, 2]` is the last one.

**Comment by longmalongma** [comment]
> I don't know... What are you trying to do? There should be three frames so `Fs[:, 2]` is the last one.



> I don't know... What are you trying to do? There should be three frames so `Fs[:, 2]` is the last one.
Fs[:, 0]是当前帧，Fs[:, 1]是前一帧，Fs[:, 2]是前一帧的前一帧，这样的理解对吗？我给你发了邮件。

**Comment by hkchengrex** [comment]
No. Fs[:, 0] is the first frame, Fs[:, 1] is the second frame, and Fs[:, 2] is the third frame. They are temporally ordered but not consecutive. You can use tensorboard to visualize the output.

You need to modify the datasets in order to load consecutive frames (see vos_dataset.py).

**Comment by longmalongma** [comment]
> No. Fs[:, 0] is the first frame, Fs[:, 1] is the second frame, and Fs[:, 2] is the third frame. They are temporally ordered but not consecutive. You can use tensorboard to visualize the output.
> 
> You need to modify the datasets in order to load consecutive frames (see vos_dataset.py).

Thanks, in that case,which one is the current frame?

**Comment by hkchengrex** [comment]
We perform two steps here. In the first step Fs[:, 1] is the current frame; in the second step Fs[:, 2] is the current frame.

**Comment by longmalongma** [comment]
> We perform two steps here. In the first step Fs[:, 1] is the current frame; in the second step Fs[:, 2] is the current frame.



> We perform two steps here. In the first step Fs[:, 1] is the current frame; in the second step Fs[:, 2] is the current frame.

Ok, I got it, thank you very much!
