### ISSUE TITLE
Out of memory was reported when batch_size=1 when testing the model

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#31]
What parameters should be changed to reduce the memory footprint when the batch_size=1 is reported to be out of memory?

**Comment by hkchengrex** [comment]
What videos are you testing on?

**Comment by longmalongma** [comment]
> What videos are you testing on?

I tested this on the youtube_vos dataset by default

**Comment by hkchengrex** [comment]
It should not run out of memory with a 11GB GPU.

**Comment by longmalongma** [comment]
> It should not run out of memory with a 11GB GPU.

@hkchengrex I'm testing my modified model, which may have more parameters and more complexity

**Comment by hkchengrex** [comment]
Well then you would need to make your own changes. General advice can be found here: https://github.com/hkchengrex/Mask-Propagation/issues/8

**Comment by longmalongma** [comment]
> Well then you would need to make your own changes. General advice can be found here: #8

@hkchengrex The easiest way is to increase the number mem_freq? Change 5 to 10?

**Comment by hkchengrex** [comment]
I have already given that suggestion in the linked issue above. So yes.

**Comment by longmalongma** [comment]
> I have already given that suggestion in the linked issue above. So yes.

Ok, thank you very much!
