### ISSUE TITLE
Does the kernelized memory need training?

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/Mask-Propagation#35]
I use the kernelized memory when evaluate STCN while did not use it when training. But the result showed a slight decrease. The raw J&F-Mean of `davis2016val` is `0.916`, `davis2017val` is `0.853`and `davis2017testdev` is `0.755` . After I use the kernelized memory, J&F-Mean of `davis2016val` is `0.913`, `davis2017val` is `0.852` and `davis2017testdev` is `0.750` . Does it because the kernelized memory need training? But why it need training since it has no trainable parameters?

**Comment by hkchengrex** [comment]
It does not need training. It *might* be because KMN is implicitly solving the memory domination problem using spatial query constraint, leading to diminishing returns when used in conjunction with STCN.
