### ISSUE TITLE
Did you use Kernel Memory (KM) in your tests?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#38]
@hkchengrex Did you use Kernel Memory (KM) in your tests? Which line is it?

![image](https://user-images.githubusercontent.com/40291722/147845403-6a9de930-8602-43be-b1b1-d78cdf3c5629.png)

**Comment by hkchengrex** [comment]
Unless a tick is specifically put under "KM", I didn't. See `eval_network.py`.
