### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for PropagationNetwork

### ISSUE THREAD

**Issue by whxueChris** [hkchengrex/Mask-Propagation#39]
Hello !  I want to train the PropagationNetwork on my personal image dataset, so I use the training command  `CUDA_VISIBLE_DEVICES=0,1 OMP_NUM_THREADS=4 python -m torch.distributed.launch --master_port 9842 --nproc_per_node=2 train.py --id retrain_s01 --load_network ./saves/propagation_model.pth --stage 0`.(based on the pretrain model  S012).  It  threw a runtime error. 

![loadnetwork_error](https://user-images.githubusercontent.com/50388024/158342877-9c5d4539-2917-4437-be72-b07edc24fa4b.JPG)
The training command works fine without the `--load network` parameters. Could you give me some suggestions?

**Comment by hkchengrex** [comment]
By default, the training goes from stage 0->3. The provided model is in stage 3, and the existing code does not support "going back" to stage 0. Basically the first conv size will not match.
Look at this method https://github.com/hkchengrex/Mask-Propagation/blob/ec9309f04ae3c98edb2eb5675c937a699d80006f/model/model.py#L188
if you want to change it.

**Comment by whxueChris** [comment]
Thanks for your reply! Expect your mentioned method, could I train my personal image cloud dataset in stage 0  and follow your next main video training?

**Comment by hkchengrex** [comment]
If I understand you correctly, you can just not load the pretrained model.

**Comment by hkchengrex** [comment]
I don't know what your data looks like but I think you need a strong temporal smoothness prior to segment clouds which our model does not provide.

**Comment by whxueChris** [comment]
I  want to solve some special object segmentation problems, such as smoke and cloud. but these kinds of datasets are lacking in the DAVIS dataset, so I want to add them the stage 0. 
The data looks like this.

![blue_patch_217_10_by_19_LC08_L1TP_061017_20160720_20170223_01_T1](https://user-images.githubusercontent.com/50388024/158934793-97bf5f7a-0f44-46d2-9952-4a81dd02e7da.jpg)
