### ISSUE TITLE
metrics results of test dataset

### ISSUE THREAD

**Issue by whxueChris** [hkchengrex/Mask-Propagation#40]
After I run the code _eval_davis_2016.py_, I only get the mask file in the output file. how could I get the value of metrics such as J, J&F?  and how could we test the model on personal datasets to get those metrics after using _interactive_gui.py_? 
Thanks for your suggestions

**Comment by hkchengrex** [comment]
1. Use DAVIS's official tool: https://davischallenge.org/
2. You cannot unless you have the ground truths.

**Comment by whxueChris** [comment]
Yes, I have the ground truths. Is it means I need to write my own code to evaluate the metrics or I can referee the DAVIS official tool?

**Comment by hkchengrex** [comment]
You can map your data into DAVIS format and use DAVIS's tool.

**Comment by whxueChris** [comment]
Thanks for your reply! It works well.
