### ISSUE TITLE
about train stage 

### ISSUE THREAD

**Issue by lsy-dot** [hkchengrex/Mask-Propagation#41]
Sorry to bother you, I plan to use my own image dataset and video dataset for training, I would like to ask if I can skip the training of stage1, i.e. use the image dataset to train stage0, use the video dataset (I have converted into the DAVIS dataset format) training stage2

**Comment by hkchengrex** [comment]
So are you skipping stage 0 or stage 1? Either is fine though.
I would recommend [STCN](https://github.com/hkchengrex/STCN) if you are working on something new as it is better than the model in this repo in almost every way. The code structure is similar so it should be easy to follow from here.

**Comment by lsy-dot** [comment]
Thank you for your prompt reply! I want to skip stage1 training, and thanks for the advice and great work!
