### ISSUE TITLE
YouTubeVOS dataset cannot be downloaded

### ISSUE THREAD

**Issue by theRain0450** [hkchengrex/Mask-Propagation#47]
I tried to go to the link in the code to download, but the link shows download error with the message as shown.
![b1a2260d-b3d5-45e9-bb58-1f60525bc706](https://github.com/hkchengrex/Mask-Propagation/assets/129521175/fca4a711-1bcc-4461-b89c-c022746709d1)

**Comment by hkchengrex** [comment]
The message basically says it. In any case, we do not maintain the YouTubeVOS dataset. Please refer to https://youtube-vos.org/
