### ISSUE TITLE
about BL30K

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#6]
您好，能把这个数据集BL30K传到百度网盘吗？BL30K这个数据集太大了，谷歌网盘有下载容量的限制，而且下载不稳定老是断。

**Comment by hkchengrex** [comment]
You can also try the OneDrive link. These are really the best options that I can provide at the moment. Baidu's one is ~100X slower for me and thus it's not an option. You can probably get a good enough performance using the first three segments if that makes things easier.

**Comment by hkchengrex** [comment]
You can also try tools with resume-download capability: https://github.com/circulosmeos/gdown.pl/tree/with-resume

**Comment by longmalongma** [comment]
> You can also try tools with resume-download capability: https://github.com/circulosmeos/gdown.pl/tree/with-resume

Ok,thanks.
