### ISSUE TITLE
How to install thinplate manually?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#7]
(mivos2) dangjisheng@ubuntui:/data/dangjisheng$ pip install git+git://github.com/cheind/py-thin-plate-spline
Collecting git+git://github.com/cheind/py-thin-plate-spline
  Cloning git://github.com/cheind/py-thin-plate-spline to /tmp/pip-g3zq_wu4-build
error: Couldn't set refs/heads/master
fatal: update_ref failed for ref 'HEAD':

How to install thinplate manually?I changed a computer and I didn't install thinplateon with the commands you provided.
Thank you very much for your help. I would like to reproduce your code as soon as possible and start some work based on your work.

**Comment by hkchengrex** [comment]
How about https://github.com/hkchengrex/Mask-Propagation/issues/2#issuecomment-806842875?

**Comment by longmalongma** [comment]
> How about [#2 (comment)](https://github.com/hkchengrex/Mask-Propagation/issues/2#issuecomment-806842875)?

soryy, it do not work, 
when I run it, problem is that：
(mivos2) dangjisheng@ubuntui:/data/dangjisheng/Mask-Propagation-main$ pip install git+git://github.com/cheind/py-thin-plate-spline

Collecting git+git://github.com/cheind/py-thin-plate-spline
  Cloning git://github.com/cheind/py-thin-plate-spline to /tmp/pip-7iflynfr-build
error: Couldn't set refs/heads/master
fatal: update_ref failed for ref 'HEAD':

**Comment by hkchengrex** [comment]
The linked comment suggested cloning the repo and installing it manually
So 
`git clone https://github.com/cheind/py-thin-plate-spline.git`
`cd py-thin-plate-spline`
`pip install -e .`

**Comment by longmalongma** [comment]
> The linked comment suggested cloning the repo and installing it manually
> So
> `git clone https://github.com/cheind/py-thin-plate-spline.git`
> `cd py-thin-plate-spline`
> `pip install -e .`

Thank you very much, I got it.
