### ISSUE TITLE
When will you release the code on the youtube dataset?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Mask-Propagation#9]
Thank you very much for your great work. When will you release the code on the youtube dataset? Am looking forward to!

**Comment by hkchengrex** [comment]
We already have the code (`eval_youtube.py`). What do you mean?

**Comment by longmalongma** [comment]
> We already have the code (`eval_youtube.py`). What do you mean?


> We already have the code (`eval_youtube.py`). What do you mean?


You only have one training script. How to train your network on DAVIS2016, DAVIS2017 and youtube datasets, respectively?

**Comment by hkchengrex** [comment]
We train one model and evaluate it on all datasets.

**Comment by longmalongma** [comment]
> We train one model and evaluate it on all datasets.

Ok,thanks for your reply!
